# api/src/routes/graphql/market-schema.gql

type Profile {
  profilePicture: String
  username: String
}

type User {
  _id: ID!
  username: String!
  profile: Profile!
  balance: Float!
  fee: Float!
}

type Product {
  _id: ID!
  name: String!
  description: String!
  price: Float!
  userId: ID!
  createdAt: String!
  updatedAt: String!
  openTrades: Int!
}

type Comment {
  _id: ID!
  user: User!
  comment: String
  rating: Float
  createdAt: String!
}

type Trade {
  _id: ID!
  product: Product!
  buyer: User!
  seller: User!
  quantity: Int!
  totalPrice: Float!
  status: String!
  createdAt: String!
}

type Query {
  getProduct(productId: ID!): Product
  getUserProducts(userId: ID!): [Product!]!
  getProductComments(productId: ID!): [Comment!]!
}
